### ISSUE TITLE
4.0.3, 4.0.4 don't load into latest .NET Interactive

### ISSUE THREAD

**Issue by dsyme** [fslaborg/XPlot#171]
I think the .NET Interactive API has changed.  I fear this is going to be a huge problem going forward.

```
Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
 ---> System.MissingMethodException: Method not found: 'Microsoft.DotNet.Interactive.DisplayedValue Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.Display(Microsoft.DotNet.Interactive.KernelInvocationContext, System.Object, System.String)'.
   at XPlot.Plotly.Interactive.KernelExtension.Microsoft.DotNet.Interactive.IKernelExtension.OnLoadAsync(Kernel kernel)
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in C:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 132
   --- End of inner exception stack trace ---
```

**Comment by cartermp** [comment]
I think this is an upstream issue - I updated this yesterday and confirmed that 4.0.4 worked with the latest .NET Interactive then.

**Comment by kkartavenka** [comment]
Actually, somehow today I received as well:

![image](https://user-images.githubusercontent.com/45607880/141213300-19a4e4cf-97ee-416a-9611-0a14ed966b8c.png)

Visual Studio Code:

Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by JasonBock** [comment]
I'm getting a very similar error. Here's the code I'm trying to run:
```
#r "nuget: XPlot.Plotly, 4.0.4"
#r "nuget: XPlot.Plotly.Interactive, 4.0.4"
#r "nuget: Collatz, 0.1.0"

using Collatz;

var position = 0;
var sequence = CollatzSequenceGenerator.Generate(5)
	.Select(_ => Tuple.Create(position++, (long)_));

var chart = Chart.Line(sequence);

chart
```

In VS, I can't copy the error, but here's a screen shot:
![image](https://user-images.githubusercontent.com/904213/141690112-983cbfa2-c945-4425-871d-384ee3de9570.png)
In VSCode, this is the error message:
```
Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at System.Reflection.RuntimeAssembly.GetExportedTypes()
at System.Reflection.Assembly.get_ExportedTypes()
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 112
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembliesInDirectory(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 74
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 47
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectoryAsync(DirectoryInfo directory, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 320
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 167
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 48
```

**Comment by JasonBock** [comment]
FWIW if I ran the cell twice the error goes away and XPlot works.

**Comment by jonsequitur** [comment]
What version number does `#!about` show?

**Comment by JasonBock** [comment]
.NET Interactive

© 2020 Microsoft Corporation

Version: 1.0.255902+b0afbdc47dec91e62b0c5cb587a0f2c24242eca8

Build date: 2021-11-14T17:01:53.8658953Z

https://github.com/dotnet/interactive

**Comment by cartermp** [comment]
Closing out, as latest XPlot.Plotly.Interactive (4.0.6) + latest .NET Interactive all work 
![image](https://user-images.githubusercontent.com/6309070/141855524-68c395ab-017b-4177-932a-2e88212b0c56.png)

**Comment by JasonBock** [comment]
Yep, all good on my machine as well :)

**Comment by cartermp** [comment]
Dope!
