### ISSUE TITLE
Doc generation no longer works

### ISSUE THREAD

**Issue by dsyme** [fslaborg/XPlot#78]
We expect

    .\build GenerateDocs

to work.  Or this with updated `dotnet fake`:

    .\build target GenerateDocs

Both fail.

**Comment by jackfoxy** [comment]
````
BuildFailedException: Target 'GenerateHelp' failed.
   StackTrace:
        at Fake.Core.TargetModule.runInternal(Boolean singleTarget, Int32 parallelJobs, String targetName, FSharpList`1 args) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 654
        at Fake.Core.TargetModule.runWithDefault$cont@795-1(Boolean allowArgs, FSharpFunc`2 fDefault, FSharpMap`2 results, Unit unitVar) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 827
        at <StartupCode$build_A205B036A1A49F0595DCEEE7A193122C0F85B77EB7644E02B8F29EEB4899A65D>.$Build$fsx.main@() in E:\GitRepos\XPlot\build.fsx:line 330
-> One or more errors occurred. (FSharp.Formatting "literate" "--processdirectory" "--layoutRoots" "E:\GitRepos\XPlot\docsrc\tools\templates" "E:\GitRepos\XPlot\packages\formatting\FSharp.Formatting\templates" "E:\GitRepos\XPlot\packages\formatting\FSharp.Formatting\templates/reference" "--inputdirectory" "E:\GitRepos\XPlot\docsrc\content" "--templatefile" "docpage.cshtml" "--outputDirectory" "E:\GitRepos\XPlot\docs" "--replacements" "root" "/XPlot" "project-name" "XPlot" "project-author" "Taha Hachana, Tomas Petricek" "project-summary" "Data visualization library for F#" "project-github" "https://github.com/fslaborg/XPlot" "project-nuget" "http://nuget.org/packages/XPlot" failed.)
-> FSharp.Formatting "literate" "--processdirectory" "--layoutRoots" "E:\GitRepos\XPlot\docsrc\tools\templates" "E:\GitRepos\XPlot\packages\formatting\FSharp.Formatting\templates" "E:\GitRepos\XPlot\packages\formatting\FSharp.Formatting\templates/reference" "--inputdirectory" "E:\GitRepos\XPlot\docsrc\content" "--templatefile" "docpage.cshtml" "--outputDirectory" "E:\GitRepos\XPlot\docs" "--replacements" "root" "/XPlot" "project-name" "XPlot" "project-author" "Taha Hachana, Tomas Petricek" "project-summary" "Data visualization library for F#" "project-github" "https://github.com/fslaborg/XPlot" "project-nuget" "http://nuget.org/packages/XPlot" failed.
   StackTrace:
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
        at Fake.DotNet.FSFormatting.run(String toolPath, String command) in D:\a\1\s\src\app\Fake.DotNet.FSFormatting\FSFormatting.fs:line 22
        at Fake.DotNet.FSFormatting.createDocs(FSharpFunc`2 p) in D:\a\1\s\src\app\Fake.DotNet.FSFormatting\FSFormatting.fs:line 61
        at Build.clo@237-20.Invoke(TargetParameter _arg1) in E:\GitRepos\XPlot\build.fsx:line 266
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 196
````

https://github.com/fsharp/FAKE/blob/66c6938c274ef949b6ce0672afe799806a0ac287/src/app/Fake.DotNet.FSFormatting/FSFormatting.fs#L22

Non-zero return from fsformatting.exe is not much help. 

This may have to do with the file  XPlot\docsrc\tools\formatters.fsx which is not converted to FAKE 5. 
I don't know how this gets run (or not) from FSharp.Formatting.

**Comment by dsyme** [comment]
@jackfoxy Do we have to use FAKE 5?  I've reverted to FAKE 4 almost every time to avoid things like this

**Comment by jackfoxy** [comment]
@dsyme Reverting to FAKE 4 makes sense. I've been successful getting FAKE 5 to work in other instances, also with docs, but not here.

**Comment by kblohm** [comment]
You might want to have a look at Deedle, i had the same problem there. That is probably less work than reverting back to FAKE 4.

**Comment by jackfoxy** [comment]
@kblohm  almost got it working with your suggestion. Still plugging away, but I think it is going to take this https://github.com/fsharp/FAKE/issues/2185 to get it done.

**Comment by dsyme** [comment]
@zyzhu Have invited you to all XPlot nuget packages
